source/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('webapp.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path, include

from webapp.views import IndexView, ProductView, ProductCreateView, \
    ProductUpdateView, ProductDeleteView, ReviewCreateView, ReviewDeleteView, ReviewUpdateView


app_name = 'webapp'


urlpatterns = [
    path('', IndexView.as_view(), name='index'),

    path('product/', include([
        path('add/', ProductCreateView.as_view(), name='product_create'),
        path('<int:pk>/', include([
            path('', ProductView.as_view(), name='product_view'),
            path('update/', ProductUpdateView.as_view(), name='product_update'),
            path('delete/', ProductDeleteView.as_view(), name='product_delete'),
            path('add_review/', ReviewCreateView.as_view(), name='review_create'),
        ])),
    ])),
    path('review/', include([
        path('<int:pk>/', include([
            path('delete/', ReviewDeleteView.as_view(), name='review_delete'),
            path('update/', ReviewUpdateView.as_view(), name='review_update'),
        ])),
    ])),
]

source/webapp/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import Avg

CATEGORY_CHOICES = (
    ('other', 'Other'),
    ('food', 'Food'),
    ('toys', 'Toys'),
    ('electronics', 'Electronics'),
    ('cars', 'Cars'),
)

GRADE_CHOICES = (
    (1, 1),
    (2, 2),
    (3, 3),
    (4, 4),
    (5, 5)
)


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='Name')
    description = models.TextField(max_length=2000, verbose_name='Description', null=True, blank=True)
    category = models.CharField(max_length=50, verbose_name='Category', choices=CATEGORY_CHOICES)
    pic = models.ImageField(null=True, blank=True, upload_to='product_pics', verbose_name='Product image')

    def __str__(self):
        return f'{self.name}'

    def get_average(self):
        avg = self.review_set.aggregate(
            Avg('grade')
        )
        avg = avg.get('grade__avg')
        if avg is not None:
            return ("%.2f" % avg)
        return 0


class Review(models.Model):
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, \
                             related_name='reviews', verbose_name='Author')
    product = models.ForeignKey('webapp.Product', on_delete=models.CASCADE, verbose_name='Product')
    text = models.TextField(max_length=1000, verbose_name='Text')
    grade = models.IntegerField(verbose_name='Grade', choices=GRADE_CHOICES)

    def __str__(self):
        return f'{self.author} for {self.product}: {self.grade}'

source/webapp/forms.py
from django import forms
from django.forms import CheckboxSelectMultiple
from webapp.models import Product, Review


class SearchForm(forms.Form):
    search = forms.CharField(max_length=50, required=False, label='Search')


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = []


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        exclude = ['author', 'product']

source/webapp/views/product_views.py
from urllib.parse import urlencode
from django.contrib.auth.mixins import UserPassesTestMixin
from django.shortcuts import reverse
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from webapp.models import Product
from webapp.forms import SearchForm, ProductForm


class IndexView(ListView):
    template_name = 'product/index.html'
    model = Product
    context_object_name = 'products'

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            queryset = queryset.filter(name__icontains=self.search_value)
        return queryset

    def get_search_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None


class ProductView(DetailView):
    template_name = 'product/product_view.html'
    model = Product


class ProductCreateView(UserPassesTestMixin, CreateView):
    template_name = 'product/product_create.html'
    form_class = ProductForm
    model = Product

    def test_func(self):
        return self.request.user.has_perm('webapp.add_product')

    def get_success_url(self):
        return reverse('webapp:product_view', kwargs={'pk': self.object.pk})


class ProductUpdateView(UserPassesTestMixin, UpdateView):
    template_name = 'product/product_update.html'
    form_class = ProductForm
    model = Product

    def test_func(self):
        return self.request.user.has_perm('webapp.change_product')

    def get_success_url(self):
        return reverse('webapp:product_view', kwargs={'pk': self.object.pk})


class ProductDeleteView(UserPassesTestMixin, DeleteView):
    template_name = 'product/product_delete.html'
    model = Product
    success_url = reverse_lazy('webapp:index')

    def test_func(self):
        return self.request.user.has_perm('webapp.delete_product')

source/webapp/views/review_views.py
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.views.generic import CreateView, DeleteView, UpdateView

from webapp.forms import ReviewForm
from webapp.models import Review, Product


class ReviewCreateView(LoginRequiredMixin, CreateView):
    model = Review
    template_name = 'review/review_create.html'
    form_class = ReviewForm

    def form_valid(self, form):
        product = get_object_or_404(Product, pk=self.kwargs.get('pk'))
        review = form.save(commit=False)
        review.product = product
        review.author = self.request.user
        review.save()
        return redirect('webapp:product_view', pk=product.pk)


class ReviewUpdateView(UserPassesTestMixin, UpdateView):
    template_name = 'review/review_update.html'
    model = Review
    form_class = ReviewForm

    def test_func(self):
        review = self.get_object()
        return self.request.user.has_perm('webapp.change_review') or review.author == self.request.user

    def get_success_url(self):
        return reverse('webapp:product_view', kwargs={'pk': self.object.product.pk})


class ReviewDeleteView(PermissionRequiredMixin, DeleteView):
    model = Review
    permission_required = 'webapp.delete_review'

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def has_permission(self):
        review = self.get_object()
        return super().has_permission() or review.author == self.request.user

    def get_success_url(self):
        return reverse('webapp:product_view', kwargs={'pk': self.object.product.pk})

source/webapp/templates/product/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Product reviewer{% endblock %}
{% block search %}
    <form class="form-inline my-lg-0" action="{% url 'webapp:index' %}" method="get">
        {% include 'partial/search.html' with button_text='Search' %}
    </form>
{% endblock %}
{% block content %}
    {% if products %}
        {% for product in products %}
            {% include 'partial/product_card.html' %}
        {% endfor %}
    {% else %}
        {% if 'search' not in request.query %}
            <h2 class="my-5">No projects yet</h2>
        {% else %}
            <h2 class="my-5">No results</h2>
        {% endif %}
    {% endif %}
    {% if request.user.is_authenticated and perms.webapp.add_product %}
        <a class="btn btn-primary btn-lg btn-block mb-4" href="{% url 'webapp:product_create' %}" role="button">Add product</a>
    {% endif %}
{% endblock %}

source/webapp/templates/product/product_create.html
{% extends "base.html" %}
{% block title %}Add product{% endblock %}
{% block content %}
    <h1>Create project</h1>
    {% url 'product_create' as action_url %}
    {% include 'partial/form.html' with button_text='Add' action_url=action_url form_method='post' enctype="multipart/form-data"%}
{% endblock %}

source/webapp/templates/product/product_delete.html
{% extends 'base.html' %}
{% block title %}Delete product{% endblock %}
{% block content %}
    <form method="post">{% csrf_token %}
        <h2 class="my-3">Are you sure you want to delete product {{ product.name }}?</h2>
        <input class="btn btn-danger" type="submit" value="Yes">
        <a class="btn btn-primary" href="{% url 'webapp:product_view' product.pk %}">No</a>
    </form>
{% endblock %}

source/webapp/templates/product/product_update.html
{% extends 'base.html' %}
{% block title %}Update product{% endblock %}
{% block content %}
    <div class="container">
        <h2 class="my-3">Update product</h2>
        {% url "product_update" pk=product.pk as action_url %}
        {% include 'partial/form.html' with action_url=action_url form_method='post' button_text='Update' enctype="multipart/form-data"%}
        <a class="btn btn-info mt-2" href="{% url 'webapp:product_view' product.pk %}" role="button">View product</a><br>
    </div>
{% endblock %}

source/webapp/templates/product/product_view.html
{% extends 'base.html' %}
{% block title %}Product {{ product.name }} {% endblock %}}
{% block content %}
    {% include 'partial/product_card.html' %}
    <hr class="mt-4">
    <h4 class="my-4">Reviews:</h4>
    {% if not product.review_set.all %}
        <p>No reviews yet</p>
    {% endif %}
    {% for review in product.review_set.all %}
        {% include 'partial/review_card.html' %}
    {% endfor %}
{% endblock %}